[[override]]
  name = "gopkg.in/fsnotify.v1"
  source = "https://github.com/fsnotify/fsnotify.git"

[[constraint]]
  name = "github.com/pborman/uuid"
  version = "1.1.0"
  
[[constraint]]        
  name = "github.com/docker/docker"
  version = "1.13.1"

[[constraint]]
  name = "github.com/pivotal-cf/brokerapi"
  version = "2.0.4"

[[constraint]]
  name = "github.com/onsi/ginkgo"
  version = "1.6.0"

[[constraint]]
  name = "k8s.io/client-go"
  version = "8.0.0"

[[override]]
  name = "k8s.io/api"
  revision = "072894a440bdee3a891dea811fe42902311cd2a3"

[[override]]
  name = "k8s.io/apimachinery"
  revision = "103fd098999dc9c0c88536f5c9ad2e5da39373ae"

[[override]]
  name = "k8s.io/kube-openapi"
  revision = "91cfa479c814065e420cee7ed227db0f63a5854e"
