[[override]]
  name = "gopkg.in/fsnotify.v1"
  source = "https://github.com/fsnotify/fsnotify.git"

[[constraint]]
  name = "github.com/pborman/uuid"
  version = "1.1.0"
  
[[constraint]]        
  name = "github.com/docker/docker"
  version = "1.13.1"

[[constraint]]
  name = "github.com/pivotal-cf/brokerapi"
  version = "2.0.4"

[[constraint]]
  name = "github.com/onsi/ginkgo"
  version = "1.6.0"
