from golang:1.11-alpine3.8 as runner

# node.js for pusher for broker to install contracts
RUN apk add --update nodejs nodejs-npm
# git for `npm install`
# gcc g++ make libc-dev for web3
RUN apk add git gcc libc-dev python make g++

RUN npm install --production --quiet cli-flags@2.0.7
RUN npm install --production --quiet web3@1.0.0-beta.36
RUN npm install --production --quiet solc@0.4.25

workdir /go/src/github.com/cloudfoundry-incubator/blockhead
copy . .

RUN go install ./vendor/github.com/onsi/ginkgo/ginkgo

cmd ["ginkgo", "-r", "-randomizeAllSpecs", "--randomizeSuites", "--keepGoing", "--cover", "--trace", "--progress"]
