from golang:1.11-alpine3.8 as builder
workdir /go/src/github.com/cloudfoundry-incubator/blockhead
copy . .
run go build -v -o /broker ./cmd/broker


from node
expose 3333
RUN npm install --production --quiet cli-flags
RUN npm install --production --quiet web3
RUN npm install --production --quiet solc
# copy in pusher.js
# 

copy --from=builder /broker /broker
copy config.json /config.json
copy services/ /services/
cmd ["/broker","/config.json", "/services"]
